[project]
name = "ground_control"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "opencv-python>=4.10.0.84",
    "pytest>=8.3.3",
    "ruff>=0.6.7",
]

[tool.uv.workspace]
members = ["tmp"]
